### ISSUE TITLE
Cannot npm install megapi

### ISSUE THREAD

**Issue by WrickColl** [Makeblock-official/NodeForMegaPi#4]
System: Raspberry Pi 3B+
Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l
node version v8.15.0

npm install megapi results in many errors. 
The main problems start when it tries to install serialport@2.0.0 which is out of date and unavailable.
It also gives warnings that hoek@2.16.3, cryptiles@2.0.5 and boom@2.10.1 are no longer supported
Tried installing the latest serialport but install megapi still tries to install the old version.
below is the last part of pi@raspberrypi:~ $ sudo cat /root/.npm/_logs/2018-12-29T03_54_49_793Z-debug.log

2114 silly install serialport@2.0.0
2115 info lifecycle serialport@2.0.0~install: serialport@2.0.0
2116 verbose lifecycle serialport@2.0.0~install: unsafe-perm in lifecycle false
2117 verbose lifecycle serialport@2.0.0~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/node_modules/megapi/node_modules/serialport/node_modules/.bin:/home/pi/node_modules/megapi/node_modules/.bin:/home/pi/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2118 verbose lifecycle serialport@2.0.0~install: CWD: /home/pi/node_modules/megapi/node_modules/serialport
2119 silly lifecycle serialport@2.0.0~install: Args: [ '-c', 'node-pre-gyp install --fallback-to-build' ]
2120 silly lifecycle serialport@2.0.0~install: Returned: code: 1  signal: null
2121 info lifecycle serialport@2.0.0~install: Failed to exec install script
2122 timing action:install Completed in 3802ms
2123 verbose unlock done using /root/.npm/_locks/staging-8a58fe8d264b10c5.lock for /home/pi/node_modules/.staging
2124 timing stage:rollbackFailedOptional Completed in 397ms
2125 timing stage:runTopLevelLifecycles Completed in 38966ms
2126 silly saveTree pi
2126 silly saveTree ├─┬ @serialport/binding-abstract@2.0.2
2126 silly saveTree │ └─┬ debug@4.1.0
2126 silly saveTree │   └── ms@2.1.1
2126 silly saveTree ├── @serialport/binding-mock@2.0.2
2126 silly saveTree ├─┬ @serialport/bindings@2.0.3
2126 silly saveTree │ ├─┬ @serialport/parser-readline@2.0.2
2126 silly saveTree │ │ └── @serialport/parser-delimiter@2.0.2
2126 silly saveTree │ ├── bindings@1.3.1
2126 silly saveTree │ ├── nan@2.11.1
2126 silly saveTree │ └─┬ prebuild-install@5.2.2
2126 silly saveTree │   ├── detect-libc@1.0.3
2126 silly saveTree │   ├── expand-template@2.0.3
2126 silly saveTree │   ├── github-from-package@0.0.0
2126 silly saveTree │   ├── minimist@1.2.0
2126 silly saveTree │   ├─┬ mkdirp@0.5.1
2126 silly saveTree │   │ └── minimist@0.0.8
2126 silly saveTree │   ├── napi-build-utils@1.0.1
2126 silly saveTree │   ├─┬ node-abi@2.5.0
2126 silly saveTree │   │ └── semver@5.6.0
2126 silly saveTree │   ├── noop-logger@0.1.1
2126 silly saveTree │   ├─┬ npmlog@4.1.2
2126 silly saveTree │   │ ├─┬ are-we-there-yet@1.1.5
2126 silly saveTree │   │ │ ├── delegates@1.0.0
2126 silly saveTree │   │ │ └─┬ readable-stream@2.3.6
2126 silly saveTree │   │ │   ├── core-util-is@1.0.2
2126 silly saveTree │   │ │   ├── inherits@2.0.3
2126 silly saveTree │   │ │   ├── isarray@1.0.0
2126 silly saveTree │   │ │   ├── process-nextick-args@2.0.0
2126 silly saveTree │   │ │   ├── safe-buffer@5.1.2
2126 silly saveTree │   │ │   ├── string_decoder@1.1.1
2126 silly saveTree │   │ │   └── util-deprecate@1.0.2
2126 silly saveTree │   │ ├── console-control-strings@1.1.0
2126 silly saveTree │   │ ├─┬ gauge@2.7.4
2126 silly saveTree │   │ │ ├── aproba@1.2.0
2126 silly saveTree │   │ │ ├── has-unicode@2.0.1
2126 silly saveTree │   │ │ ├── object-assign@4.1.1
2126 silly saveTree │   │ │ ├── signal-exit@3.0.2
2126 silly saveTree │   │ │ ├─┬ string-width@1.0.2
2126 silly saveTree │   │ │ │ ├── code-point-at@1.1.0
2126 silly saveTree │   │ │ │ ├─┬ is-fullwidth-code-point@1.0.0
2126 silly saveTree │   │ │ │ │ └── number-is-nan@1.0.1
2126 silly saveTree │   │ │ │ └─┬ strip-ansi@3.0.1
2126 silly saveTree │   │ │ │   └── ansi-regex@2.1.1
2126 silly saveTree │   │ │ ├── strip-ansi@3.0.1
2126 silly saveTree │   │ │ └── wide-align@1.1.3
2126 silly saveTree │   │ └── set-blocking@2.0.0
2126 silly saveTree │   ├── os-homedir@1.0.2
2126 silly saveTree │   ├─┬ pump@2.0.1
2126 silly saveTree │   │ ├─┬ end-of-stream@1.4.1
2126 silly saveTree │   │ │ └─┬ once@1.4.0
2126 silly saveTree │   │ │   └── wrappy@1.0.2
2126 silly saveTree │   │ └── once@1.4.0
2126 silly saveTree │   ├─┬ rc@1.2.8
2126 silly saveTree │   │ ├── deep-extend@0.6.0
2126 silly saveTree │   │ ├── ini@1.3.5
2126 silly saveTree │   │ └── strip-json-comments@2.0.1
2126 silly saveTree │   ├─┬ simple-get@2.8.1
2126 silly saveTree │   │ ├─┬ decompress-response@3.3.0
2126 silly saveTree │   │ │ └── mimic-response@1.0.1
2126 silly saveTree │   │ └── simple-concat@1.0.0
2126 silly saveTree │   ├─┬ tar-fs@1.16.3
2126 silly saveTree │   │ ├── chownr@1.1.1
2126 silly saveTree │   │ ├── pump@1.0.3
2126 silly saveTree │   │ └─┬ tar-stream@1.6.2
2126 silly saveTree │   │   ├── bl@1.2.2
2126 silly saveTree │   │   ├─┬ buffer-alloc@1.2.0
2126 silly saveTree │   │   │ ├── buffer-alloc-unsafe@1.1.0
2126 silly saveTree │   │   │ └── buffer-fill@1.0.0
2126 silly saveTree │   │   ├── fs-constants@1.0.0
2126 silly saveTree │   │   ├── to-buffer@1.1.1
2126 silly saveTree │   │   └── xtend@4.0.1
2126 silly saveTree │   ├── tunnel-agent@0.6.0
2126 silly saveTree │   └── which-pm-runs@1.0.0
2126 silly saveTree ├── @serialport/parser-byte-length@2.0.2
2126 silly saveTree ├── @serialport/parser-cctalk@2.0.2
2126 silly saveTree ├── @serialport/parser-delimiter@2.0.2
2126 silly saveTree ├── @serialport/parser-readline@2.0.2
2126 silly saveTree ├── @serialport/parser-ready@2.0.2
2126 silly saveTree ├── @serialport/parser-regex@2.0.2
2126 silly saveTree ├── @serialport/stream@2.0.2
2126 silly saveTree ├─┬ accepts@1.3.5
2126 silly saveTree │ ├─┬ mime-types@2.1.21
2126 silly saveTree │ │ └── mime-db@1.37.0
2126 silly saveTree │ └── negotiator@0.6.1
2126 silly saveTree ├── after@0.8.2
2126 silly saveTree ├── ansi-regex@2.1.1
2126 silly saveTree ├── aproba@1.2.0
2126 silly saveTree ├── are-we-there-yet@1.1.5
2126 silly saveTree ├── arraybuffer.slice@0.0.7
2126 silly saveTree ├── async-limiter@1.0.0
2126 silly saveTree ├── backo2@1.0.2
2126 silly saveTree ├── base64-arraybuffer@0.1.5
2126 silly saveTree ├── base64id@1.0.0
2126 silly saveTree ├─┬ better-assert@1.0.2
2126 silly saveTree │ └── callsite@1.0.0
2126 silly saveTree ├── bindings@1.3.1
2126 silly saveTree ├── bl@1.2.2
2126 silly saveTree ├── blob@0.0.5
2126 silly saveTree ├─┬ boom@7.3.0
2126 silly saveTree │ └── hoek@6.1.2
2126 silly saveTree ├── buffer-alloc-unsafe@1.1.0
2126 silly saveTree ├── buffer-alloc@1.2.0
2126 silly saveTree ├── buffer-fill@1.0.0
2126 silly saveTree ├── callsite@1.0.0
2126 silly saveTree ├── chownr@1.1.1
2126 silly saveTree ├── code-point-at@1.1.0
2126 silly saveTree ├── component-bind@1.0.0
2126 silly saveTree ├── component-emitter@1.2.1
2126 silly saveTree ├── component-inherit@0.0.3
2126 silly saveTree ├── console-control-strings@1.1.0
2126 silly saveTree ├── cookie@0.3.1
2126 silly saveTree ├── core-util-is@1.0.2
2126 silly saveTree ├── cryptiles@4.1.3
2126 silly saveTree ├── debug@4.1.0
2126 silly saveTree ├── decompress-response@3.3.0
2126 silly saveTree ├── deep-extend@0.6.0
2126 silly saveTree ├── delegates@1.0.0
2126 silly saveTree ├── detect-libc@1.0.3
2126 silly saveTree ├── end-of-stream@1.4.1
2126 silly saveTree ├─┬ engine.io-client@3.3.1
2126 silly saveTree │ ├─┬ debug@3.1.0
2126 silly saveTree │ │ └── ms@2.0.0
2126 silly saveTree │ ├─┬ engine.io-parser@2.1.3
2126 silly saveTree │ │ └─┬ has-binary2@1.0.3
2126 silly saveTree │ │   └── isarray@2.0.1
2126 silly saveTree │ ├── has-cors@1.1.0
2126 silly saveTree │ ├── indexof@0.0.1
2126 silly saveTree │ ├── parseqs@0.0.5
2126 silly saveTree │ ├── parseuri@0.0.5
2126 silly saveTree │ ├── ws@6.1.2
2126 silly saveTree │ ├── xmlhttprequest-ssl@1.5.5
2126 silly saveTree │ └── yeast@0.1.2
2126 silly saveTree ├── engine.io-parser@2.1.3
2126 silly saveTree ├─┬ engine.io@3.3.2
2126 silly saveTree │ └─┬ debug@3.1.0
2126 silly saveTree │   └── ms@2.0.0
2126 silly saveTree ├─┬ epoll@2.0.7
2126 silly saveTree │ └── nan@2.12.1
2126 silly saveTree ├── expand-template@2.0.3
2126 silly saveTree ├── fs-constants@1.0.0
2126 silly saveTree ├── gauge@2.7.4
2126 silly saveTree ├── github-from-package@0.0.0
2126 silly saveTree ├── has-binary2@1.0.3
2126 silly saveTree ├── has-cors@1.1.0
2126 silly saveTree ├── has-unicode@2.0.1
2126 silly saveTree ├── hoek@6.1.2
2126 silly saveTree ├── indexof@0.0.1
2126 silly saveTree ├── inherits@2.0.3
2126 silly saveTree ├── ini@1.3.5
2126 silly saveTree ├── is-fullwidth-code-point@1.0.0
2126 silly saveTree ├── isarray@1.0.0
2126 silly saveTree ├── lodash.debounce@4.0.8
2126 silly saveTree ├─┬ megapi@0.1.3
2126 silly saveTree │ └─┬ serialport@2.0.0
2126 silly saveTree │   ├── async@0.9.0
2126 silly saveTree │   ├── bindings@1.2.1
2126 silly saveTree │   ├─┬ debug@2.6.9
2126 silly saveTree │   │ └── ms@2.0.0
2126 silly saveTree │   ├── nan@2.0.9
2126 silly saveTree │   ├─┬ node-pre-gyp@0.6.39
2126 silly saveTree │   │ ├─┬ hawk@3.1.3
2126 silly saveTree │   │ │ ├─┬ boom@2.10.1
2126 silly saveTree │   │ │ │ └── hoek@2.16.3
2126 silly saveTree │   │ │ ├── cryptiles@2.0.5
2126 silly saveTree │   │ │ ├── hoek@2.16.3
2126 silly saveTree │   │ │ └─┬ sntp@1.0.9
2126 silly saveTree │   │ │   └── hoek@2.16.3
2126 silly saveTree │   │ ├─┬ nopt@4.0.1
2126 silly saveTree │   │ │ ├── abbrev@1.1.1
2126 silly saveTree │   │ │ └─┬ osenv@0.1.5
2126 silly saveTree │   │ │   └── os-tmpdir@1.0.2
2126 silly saveTree │   │ ├─┬ request@2.81.0
2126 silly saveTree │   │ │ ├── aws-sign2@0.6.0
2126 silly saveTree │   │ │ ├── aws4@1.8.0
2126 silly saveTree │   │ │ ├── caseless@0.12.0
2126 silly saveTree │   │ │ ├─┬ combined-stream@1.0.7
2126 silly saveTree │   │ │ │ └── delayed-stream@1.0.0
2126 silly saveTree │   │ │ ├── extend@3.0.2
2126 silly saveTree │   │ │ ├── forever-agent@0.6.1
2126 silly saveTree │   │ │ ├─┬ form-data@2.1.4
2126 silly saveTree │   │ │ │ └── asynckit@0.4.0
2126 silly saveTree │   │ │ ├─┬ har-validator@4.2.1
2126 silly saveTree │   │ │ │ ├─┬ ajv@4.11.8
2126 silly saveTree │   │ │ │ │ ├── co@4.6.0
2126 silly saveTree │   │ │ │ │ └─┬ json-stable-stringify@1.0.1
2126 silly saveTree │   │ │ │ │   └── jsonify@0.0.0
2126 silly saveTree │   │ │ │ └── har-schema@1.0.5
2126 silly saveTree │   │ │ ├─┬ http-signature@1.1.1
2126 silly saveTree │   │ │ │ ├── assert-plus@0.2.0
2126 silly saveTree │   │ │ │ ├─┬ jsprim@1.4.1
2126 silly saveTree │   │ │ │ │ ├── assert-plus@1.0.0
2126 silly saveTree │   │ │ │ │ ├── extsprintf@1.3.0
2126 silly saveTree │   │ │ │ │ ├── json-schema@0.2.3
2126 silly saveTree │   │ │ │ │ └─┬ verror@1.10.0
2126 silly saveTree │   │ │ │ │   └── assert-plus@1.0.0
2126 silly saveTree │   │ │ │ └─┬ sshpk@1.16.0
2126 silly saveTree │   │ │ │   ├─┬ asn1@0.2.4
2126 silly saveTree │   │ │ │   │ └── safer-buffer@2.1.2
2126 silly saveTree │   │ │ │   ├── assert-plus@1.0.0
2126 silly saveTree │   │ │ │   ├─┬ bcrypt-pbkdf@1.0.2
2126 silly saveTree │   │ │ │   │ └── tweetnacl@0.14.5
2126 silly saveTree │   │ │ │   ├─┬ dashdash@1.14.1
2126 silly saveTree │   │ │ │   │ └── assert-plus@1.0.0
2126 silly saveTree │   │ │ │   ├─┬ ecc-jsbn@0.1.2
2126 silly saveTree │   │ │ │   │ └── jsbn@0.1.1
2126 silly saveTree │   │ │ │   ├─┬ getpass@0.1.7
2126 silly saveTree │   │ │ │   │ └── assert-plus@1.0.0
2126 silly saveTree │   │ │ │   ├── jsbn@0.1.1
2126 silly saveTree │   │ │ │   ├── safer-buffer@2.1.2
2126 silly saveTree │   │ │ │   └── tweetnacl@0.14.5
2126 silly saveTree │   │ │ ├── is-typedarray@1.0.0
2126 silly saveTree │   │ │ ├── isstream@0.1.2
2126 silly saveTree │   │ │ ├── json-stringify-safe@5.0.1
2126 silly saveTree │   │ │ ├── oauth-sign@0.8.2
2126 silly saveTree │   │ │ ├── performance-now@0.2.0
2126 silly saveTree │   │ │ ├── qs@6.4.0
2126 silly saveTree │   │ │ ├── stringstream@0.0.6
2126 silly saveTree │   │ │ ├─┬ tough-cookie@2.3.4
2126 silly saveTree │   │ │ │ └── punycode@1.4.1
2126 silly saveTree │   │ │ └── uuid@3.3.2
2126 silly saveTree │   │ ├─┬ rimraf@2.6.2
2126 silly saveTree │   │ │ └─┬ glob@7.1.3
2126 silly saveTree │   │ │   ├── fs.realpath@1.0.0
2126 silly saveTree │   │ │   ├── inflight@1.0.6
2126 silly saveTree │   │ │   ├─┬ minimatch@3.0.4
2126 silly saveTree │   │ │   │ └─┬ brace-expansion@1.1.11
2126 silly saveTree │   │ │   │   ├── balanced-match@1.0.0
2126 silly saveTree │   │ │   │   └── concat-map@0.0.1
2126 silly saveTree │   │ │   └── path-is-absolute@1.0.1
2126 silly saveTree │   │ ├─┬ tar-pack@3.4.1
2126 silly saveTree │   │ │ ├─┬ debug@2.6.9
2126 silly saveTree │   │ │ │ └── ms@2.0.0
2126 silly saveTree │   │ │ ├─┬ fstream-ignore@1.0.5
2126 silly saveTree │   │ │ │ └─┬ fstream@1.0.11
2126 silly saveTree │   │ │ │   └── graceful-fs@4.1.15
2126 silly saveTree │   │ │ ├── fstream@1.0.11
2126 silly saveTree │   │ │ ├─┬ tar@2.2.1
2126 silly saveTree │   │ │ │ └── block-stream@0.0.9
2126 silly saveTree │   │ │ └── uid-number@0.0.6
2126 silly saveTree │   │ └── tar@2.2.1
2126 silly saveTree │   ├─┬ optimist@0.6.1
2126 silly saveTree │   │ ├── minimist@0.0.10
2126 silly saveTree │   │ └── wordwrap@0.0.3
2126 silly saveTree │   └── sf@0.1.7
2126 silly saveTree ├── mime-db@1.37.0
2126 silly saveTree ├── mime-types@2.1.21
2126 silly saveTree ├── mimic-response@1.0.1
2126 silly saveTree ├── minimist@1.2.0
2126 silly saveTree ├── mkdirp@0.5.1
2126 silly saveTree ├── ms@2.1.1
2126 silly saveTree ├── nan@2.11.1
2126 silly saveTree ├── napi-build-utils@1.0.1
2126 silly saveTree ├── negotiator@0.6.1
2126 silly saveTree ├── node-abi@2.5.0
2126 silly saveTree ├── noop-logger@0.1.1
2126 silly saveTree ├── npmlog@4.1.2
2126 silly saveTree ├── number-is-nan@1.0.1
2126 silly saveTree ├── object-assign@4.1.1
2126 silly saveTree ├── object-component@0.0.3
2126 silly saveTree ├── once@1.4.0
2126 silly saveTree ├── onoff@3.2.2
2126 silly saveTree ├── os-homedir@1.0.2
2126 silly saveTree ├── parseqs@0.0.5
2126 silly saveTree ├── parseuri@0.0.5
2126 silly saveTree ├─┬ pigpio@1.2.1
2126 silly saveTree │ └── nan@2.12.1
2126 silly saveTree ├── prebuild-install@5.2.2
2126 silly saveTree ├── process-nextick-args@2.0.0
2126 silly saveTree ├── pump@2.0.1
2126 silly saveTree ├── rc@1.2.8
2126 silly saveTree ├── readable-stream@2.3.6
2126 silly saveTree ├── safe-buffer@5.1.2
2126 silly saveTree ├── semver@5.6.0
2126 silly saveTree ├── set-blocking@2.0.0
2126 silly saveTree ├── signal-exit@3.0.2
2126 silly saveTree ├── simple-concat@1.0.0
2126 silly saveTree ├── simple-get@2.8.1
2126 silly saveTree ├── socket.io-adapter@1.1.1
2126 silly saveTree ├─┬ socket.io-client@2.2.0
2126 silly saveTree │ ├─┬ debug@3.1.0
2126 silly saveTree │ │ └── ms@2.0.0
2126 silly saveTree │ ├─┬ socket.io-parser@3.3.0
2126 silly saveTree │ │ ├─┬ debug@3.1.0
2126 silly saveTree │ │ │ └── ms@2.0.0
2126 silly saveTree │ │ └── isarray@2.0.1
2126 silly saveTree │ └── to-array@0.1.4
2126 silly saveTree ├── socket.io-parser@3.3.0
2126 silly saveTree ├── socket.io@2.2.0
2126 silly saveTree ├── string_decoder@1.1.1
2126 silly saveTree ├── string-width@1.0.2
2126 silly saveTree ├── strip-ansi@3.0.1
2126 silly saveTree ├── strip-json-comments@2.0.1
2126 silly saveTree ├── tar-fs@1.16.3
2126 silly saveTree ├── tar-stream@1.6.2
2126 silly saveTree ├── to-array@0.1.4
2126 silly saveTree ├── to-buffer@1.1.1
2126 silly saveTree ├── tunnel-agent@0.6.0
2126 silly saveTree ├── util-deprecate@1.0.2
2126 silly saveTree ├── which-pm-runs@1.0.0
2126 silly saveTree ├── wide-align@1.1.3
2126 silly saveTree ├── wrappy@1.0.2
2126 silly saveTree ├── ws@6.1.2
2126 silly saveTree ├── xmlhttprequest-ssl@1.5.5
2126 silly saveTree ├── xtend@4.0.1
2126 silly saveTree └── yeast@0.1.2
2127 warn serialport@2.0.0 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions.
2128 warn enoent ENOENT: no such file or directory, open '/home/pi/package.json'
2129 verbose enoent This is related to npm not being able to find a file.
2130 warn pi No description
2131 warn pi No repository field.
2132 warn pi No README data
2133 warn pi No license field.
2134 verbose stack Error: serialport@2.0.0 install: `node-pre-gyp install --fallback-to-build`
2134 verbose stack Exit status 1
2134 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
2134 verbose stack     at emitTwo (events.js:126:13)
2134 verbose stack     at EventEmitter.emit (events.js:214:7)
2134 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2134 verbose stack     at emitTwo (events.js:126:13)
2134 verbose stack     at ChildProcess.emit (events.js:214:7)
2134 verbose stack     at maybeClose (internal/child_process.js:915:16)
2134 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2135 verbose pkgid serialport@2.0.0
2136 verbose cwd /home/pi
2137 verbose Linux 4.14.79-v7+
2138 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "megapi"
2139 verbose node v8.15.0
2140 verbose npm  v6.4.1
2141 error code ELIFECYCLE
2142 error errno 1
2143 error serialport@2.0.0 install: `node-pre-gyp install --fallback-to-build`
2143 error Exit status 1
2144 error Failed at the serialport@2.0.0 install script.
2144 error This is probably not a problem with npm. There is likely additional logging output above.
2145 verbose exit [ 1, true ]
pi@raspberrypi:~ $

**Comment by WrickColl** [comment]
Please fix this problem. It is impossible to use "nodejs" with megapi by following the instructions in the README 
In other words, the version you get when you try to 'npm install megapi' is grossly out of date and does not install anything.

**Comment by WrickColl** [comment]
oops accidentally closed issue. The issue is still a problem
